### ISSUE TITLE
Funtion error : randn return org.apache.hadoop.hbase.DoNotRetryIOException

### ISSUE THREAD

**Issue by pzzs** [Huawei-Spark/hbase#11] opened 2015-07-10 08:58 UTC
I get this test from JavaDataFrameSuite.java

Table

```
grade            int
class            int
subject          string  
teacher _name    string
teacher _age     int

keyCols : grade,class,subject
```

Data 

```
1,1,subject_1,teacher_1_1_1,25
1,1,subject_2,teacher_1_2_1,25
1,1,subject_3,teacher_1_3_1,25
1,1,subject_4,teacher_1_4_1,25
1,1,subject_5,teacher_1_5_1,25
1,2,subject_1,teacher_1_1_1,25
1,2,subject_2,teacher_1_2_1,25
1,2,subject_3,teacher_1_3_1,25
1,2,subject_4,teacher_1_4_1,25
1,2,subject_5,teacher_1_5_1,25
1,3,subject_1,teacher_1_1_1,25
1,3,subject_2,teacher_1_2_1,25
...
...
```

Info

```
scala> teachers.select(rand, acos("teacher_age")).show(1);
15/07/10 16:51:18 WARN TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0, 9.91.8.153): org.apache.hadoop.hbase.DoNotRetryIOException: Failed after retry of OutOfOrderScannerNextException: was there a rpc timeout?
        at org.apache.hadoop.hbase.client.ClientScanner.next(ClientScanner.java:403)
        at org.apache.spark.sql.hbase.HBasePostCoprocessorSQLReaderRDD$$anon$1.hasNext(HBaseSQLReaderRDD.scala:119)
        at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:39)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:308)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:103)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:47)
        at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:273)
        at scala.collection.AbstractIterator.to(Iterator.scala:1157)
        at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:265)
        at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1157)
        at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:252)
        at scala.collection.AbstractIterator.toArray(Iterator.scala:1157)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$3.apply(SparkPlan.scala:143)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$3.apply(SparkPlan.scala:143)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1765)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1765)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:63)
        at org.apache.spark.scheduler.Task.run(Task.scala:70)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:722)
Caused by: org.apache.hadoop.hbase.exceptions.OutOfOrderScannerNextException: org.apache.hadoop.hbase.exceptions.OutOfOrderScannerNextException: Expected nextCallSeq: 1 But the nextCallSeq got from client: 0; request=scanner_id: 89 number_of_rows: 1000 close_scanner: false next_call_seq: 0
        at org.apache.hadoop.hbase.regionserver.RSRpcServices.scan(RSRpcServices.java:2061)
        at org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:31443)
        at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2031)
        at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:107)
        at org.apache.hadoop.hbase.ipc.RpcExecutor.consumerLoop(RpcExecutor.java:130)
        at org.apache.hadoop.hbase.ipc.RpcExecutor$1.run(RpcExecutor.java:107)
        at java.lang.Thread.run(Thread.java:722)

        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
        at org.apache.hadoop.hbase.RemoteExceptionHandler.decodeRemoteException(RemoteExceptionHandler.java:97)
        at org.apache.hadoop.hbase.client.ScannerCallable.call(ScannerCallable.java:214)
        at org.apache.hadoop.hbase.client.ScannerCallable.call(ScannerCallable.java:59)
        at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:114)
        at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:90)
        at org.apache.hadoop.hbase.client.ClientScanner.next(ClientScanner.java:355)
        ... 25 more

```

the status of hbase is good.

**Comment by xinyunh** [comment] 2015-07-11 18:33
Solved and merged into branch Stratio-ToSpark1_4 
(https://github.com/Huawei-Spark/hbase/commit/0169bf3856d788c25c1c4a77e70fed16313ef1b0)

Thanks!

**Comment by pzzs** [comment] 2015-07-13 07:31
I test it  and i get OutOfOrderScannerNextException again. please checkout it. @xinyunh @yzhou2001

**Comment by pzzs** [comment] 2015-07-13 07:32
The branch that i used is master.

**Comment by yzhou2001** [comment] 2015-07-13 14:16
@DoingDone9 Please make sure your build after the fix is deployed to the HBase slave machines as well. To do that, you should first shut down your HBase cluster, scp the spark-hbase jar (with the fix of course) to the HBase slaves, then restart the HBase cluster.

We tested the fix on our environment and it works. If confirmed that this is still a problem, please reopen this issue. Thanks.

**Comment by pzzs** [comment] 2015-07-14 07:00
This is not happened every time. I test many times and get  exception twice.

**Comment by yzhou2001** [comment] 2015-07-14 14:37
@DoingDone9  It's a nice catch! We'll fix it for sure. Many thanks!

**Comment by xinyunh** [comment] 2015-07-14 23:12
Fixed and merged into master (https://github.com/Huawei-Spark/SparkSQL-on-HBase/commit/c4afac0d837724d848de8631a847e79fea84f3da)

Thanks!

**Comment by pzzs** [comment] 2015-07-16 03:29
I test it and this exception happened every time when spark.sql.hbase.coprocessor=true and spark.sql.hbase.customfilter=true @xinyunh

**Comment by xinyunh** [comment] 2015-07-16 03:32
I will check it.

**Comment by pzzs** [comment] 2015-07-16 03:34
My number is p00251601. you can call me if necessary.

**Comment by pzzs** [comment] 2015-07-16 03:41
sorry. " teachers.select(rand, acos("teacher_age")).show(1) "  is wrong. "teachers.select(col("*"), randn(5L)).show(1)" is right. @xinyunh

**Comment by yzhou2001** [comment] 2015-07-16 03:54
@DoingDone9  So this problem occurs only when BOTH coprocessor AND CustomFilter are true? If we remove col("_"), will it occur? How about if we remove randn and just leave col(_)?

**Comment by pzzs** [comment] 2015-07-16 04:03
"teachers.select(rand, acos("teacher_age")).show(1)" is Error with coprocessor is true.  @yzhou2001  @xinyunh 

"teachers.select(col("*"), randn(5L)).show(1)" is good .

**Comment by xinyunh** [comment] 2015-07-16 06:49
@DoingDone9  May I have your phone number？

**Comment by pzzs** [comment] 2015-07-16 06:50
15067181331

**Comment by xinyunh** [comment] 2015-07-16 07:22
Fixed and merged into master (https://github.com/Huawei-Spark/SparkSQL-on-HBase/commit/7f00fa0dd5471251856cde6f221bd98438005ddd)

Thanks!

**Closed as completed by xinyunh** 2015-07-16 07:22 UTC

**Comment by pzzs** [comment] 2015-07-16 07:29
Can you fix it to https://github.com/Huawei-Spark/Spark-SQL-on-HBase. @xinyunh

**Comment by xinyunh** [comment] 2015-07-16 07:38
@DoingDone9 
I got errors in building that one. Thus, let me check with @yzhou2001 first tomorrow.
As soon as the building success, I will checkin this change. :-)

**Comment by pzzs** [comment] 2015-07-16 07:49
OK. i build it successfully

**Comment by xinyunh** [comment] 2015-07-16 07:50
@DoingDone9 
Err...I also got passed this time...
OK, I will checkin the change soon.

**Comment by xinyunh** [comment] 2015-07-16 08:02
@DoingDone9 
Checkin to the  https://github.com/Huawei-Spark/Spark-SQL-on-HBase

**Comment by yzhou2001** [comment] 2015-07-16 08:05
@DoingDone9
Please retest it.

**Comment by pzzs** [comment] 2015-07-16 08:07
OK

**Comment by pzzs** [comment] 2015-07-16 08:17
It has been fixed! :+1:

**Comment by yzhou2001** [comment] 2015-07-16 08:24
I just fixed some README problem (Step 1 of the build process wasn't accurate). Please make sure you, @DoingDone9,  did not follow the wrong step, i.e., from the wrong repo,  when you did the clone.
Thanks.

**Comment by pzzs** [comment] 2015-07-16 08:28
get it

**Comment by yzhou2001** [comment] 2015-07-16 08:33
@DoingDone9  If you find no error by today's end, please give us a green light so I can build a package tomorrow (actually today since it's already 1:32AM here is U.S.) at the earliest moment.

**Comment by pzzs** [comment] 2015-07-16 08:35
ok
