### ISSUE TITLE
Error of group by  : Return error result and get ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by pzzs** [Huawei-Spark/hbase#6] opened 2015-07-09 05:04 UTC
table :

```
TableName  :
Spark ：spark_teacher_3key
Hbse ：hbase_ teacher_3key

Field :
grade         int
class          int
subject        String  
teacher _name        string
teacher _age          int

create table sql :

CREATE TABLE spark_teacher_3key(grade int, class int, subject string, teacher_name string, teacher_age int, PRIMARY KEY (grade, class, subject)) MAPPED BY (hbase_teacher_3key, COLS=[teacher_name=teacher.name, teacher_age=teacher.age]);
```

data ：

```
1,1,subject_1,teacher_1_1_1,25
1,1,subject_2,teacher_1_2_1,25
1,1,subject_3,teacher_1_3_1,25
1,1,subject_4,teacher_1_4_1,25
1,1,subject_5,teacher_1_5_1,25
1,2,subject_1,teacher_1_1_1,25
1,2,subject_2,teacher_1_2_1,25
1,2,subject_3,teacher_1_3_1,25
1,2,subject_4,teacher_1_4_1,25
1,2,subject_5,teacher_1_5_1,25
1,3,subject_1,teacher_1_1_1,25
1,3,subject_2,teacher_1_2_1,25
.......
.......
```

Question_1:

```
select count(*) from spark_teacher_3key where grade=1 and class=3  and subject='subject_1' group by teacher_name; 

Result :
[teacher_1_1_2]

i think the result should be 1

```

Question_2:

```
select count(teacher_age) from spark_teacher_3key where grade=1 and class=3  and subject='subject_1' group by teacher_name;

error :
spark-hbaseql> select count(teacher_age) from spark_teacher_3key where grade=1 and class=3  and subject='subject_1' group by teacher_name;
15/07/09 12:58:23 WARN TaskSetManager: Lost task 0.0 in stage 11.0 (TID 17, 9.91.8.153): java.lang.ArrayIndexOutOfBoundsException: 1
        at org.apache.spark.sql.catalyst.CatalystTypeConverters$.convertRowWithConverters(CatalystTypeConverters.scala:348)
        at org.apache.spark.sql.catalyst.CatalystTypeConverters$$anonfun$createToScalaConverter$4.apply(CatalystTypeConverters.scala:301)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$1$$anonfun$apply$1.apply(SparkPlan.scala:104)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$1$$anonfun$apply$1.apply(SparkPlan.scala:104)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)

```

**Comment by yzhou2001** [comment] 2015-07-09 06:28
This seems to be real problem. I'll work on it tomorrow. Thanks for catching!

**Comment by DoingDone9** [comment] 2015-07-10 06:17
yes,   "select * from spark_teacher_3key_df order by grade limit 2" has the same problem. But "select * from spark_teacher_3key_df sort by grade limit 2" is good.

**Comment by yzhou2001** [comment] 2015-07-10 22:13
The problem is that, for a multidimensional point query, the original scan's projection is used for the post coprocessor scan. It should be the subplan's projection.

Fixed by not using coprocessor at all for point queries since point queries are very fast and do not justify the use of coprocessor considering its overheads.

**Closed as completed by yzhou2001** 2015-07-10 22:13 UTC
