### ISSUE TITLE
Spark does't return the first cf

### ISSUE THREAD

**Issue by josegom** [Huawei-Spark/hbase#5] opened 2015-07-02 09:11 UTC
Hi,
I am using the branch Stratio-Spark v1_4. My environment is the following
hbase 1.0.1.1
spark 1.4

I have inserted a set of rows in Hbase:

``` hbase
hbase(main):001:0> scan 'test'
ROW                                                          COLUMN+CELL                                                                                                                                                                    
 row1                                                        column=cf:a, timestamp=1434961121748, value=value1                                                                                                                               
 row1                                                        column=cf:b, timestamp=1434965778840, value=value8                                                                                                                               
 row1                                                        column=cf:c, timestamp=1434965776281, value=value8                                                                                                                               
 row2                                                        column=cf:a, timestamp=1434965769169, value=value8                                                                                                                               
 row2                                                        column=cf:b, timestamp=1434961127371, value=value2                                                                                                                               
 row2                                                        column=cf:c, timestamp=1434965772167, value=value8                                                                                                                               
 row3                                                        column=cf:a, timestamp=1434965758996, value=value8                                                                                                                               
 row3                                                        column=cf:b, timestamp=1434965756485, value=value8                                                                                                                               
 row3                                                        column=cf:c, timestamp=1434961140225, value=value3                                                                                                                               
 row4                                                        column=cf:a, timestamp=1434965641489, value=value8                                                                                                                               
 row4                                                        column=cf:b, timestamp=1434965727107, value=value8                                                                                                                               
 row4                                                        column=cf:c, timestamp=1434965730322, value=value8                                                                                                                               
4 row(s) in 0.1860 seconds
```

And my scala code is the following::

``` scala
  val conf = new SparkConf()
    .setMaster(SPARK_IP)
    .setAppName("poc-hbase-test")
  val sc = new SparkContext(conf)
  val hbaseContext =  new HBaseSQLContext(sc)
  hbaseContext.read.format(DATASOURCE).options( Map("namespace" -> "", "tableName" -> "testSpark3", "hbaseTableName" -> "test",  "colsSeq" -> "cf:a,cf:b,cf:c", "keyCols" -> "cf:a,string", "nonKeyCols" -> "cf:b,string,cf,b;cf:c,integer,cf,c")) .load
```

Later I execute 

``` scala
  System.out.println("First output")
   hbaseContext.sql("Select  `cf:b` as b from testSpark2").collect.foreach(print)
  System.out.println("Second output")
  hbaseContext.sql("Select  `cf:a` as b from testSpark3").collect.foreach(print)
```

and the output is

``` scala
First output
[value8]
[value2]
[value8]
[value8]
Second output
[]
[]
[]
[]
```

The first query is right but the second query doesn't return anything and it should return:

``` scala
[value1]
[value8]
[value8]
[value8]
```

can Anybody  help me?

**Comment by yzhou2001** [comment] 2015-07-03 02:21
I agree it should not return empty rows, but it shouldn't return [value1], ..., [value8] either. Instead, it should return [row1], ..., [row4] because "cf:a" is a row-key column.

Can you confirm, or post your full source? I have not rerun your DF method. But from my SQL runs, they seem to be ok.

**Comment by josegom** [comment] 2015-07-03 11:47
Hello,
I have made another example to clarify the issue.

I have exeute the folowing code in hbase shell:

``` hbase
 create 'students', 'personal_data', 'school_data'
 put 'students', 'id1', 'personal_data:name' , 'jose'
 put 'students', 'id1', 'personal_data:age', 30
 put 'students', 'id1', 'personal_data:identification', '123'
 put 'students', 'id1', 'school_data:identification', 'ABC'
 put 'students', 'id1', 'school_data:direction', 'main street'
 put 'students', 'id2', 'personal_data:name' , 'loreto'
 put 'students', 'id2', 'personal_data:age', 28
 put 'students', 'id2', 'personal_data:identification', '1235'
 put 'students', 'id2', 'school_data:identification', 'ABCR'
 put 'students', 'id2', 'school_data:direction', 'main street'
 put 'students', 'id3', 'personal_data:name' , 'cristian'
 put 'students', 'id3', 'personal_data:age', 33
 put 'students', 'id3', 'personal_data:identification', 'A1235'
 put 'students', 'id3', 'school_data:identification', 'TBCR'
 put 'students', 'id3', 'school_data:direction', 'other street'

   scan 'students'

ROW                                                          COLUMN+CELL                                                                                                                                                                      
 id1                                                         column=personal_data:age, timestamp=1435922549884, value=30                                                                                                                      
 id1                                                         column=personal_data:identification, timestamp=1435922627507, value=123                                                                                                          
 id1                                                         column=personal_data:name, timestamp=1435922475679, value=jose                                                                                                                   
 id1                                                         column=school_data:direction, timestamp=1435922628423, value=main street                                                                                                         
 id1                                                         column=school_data:identification, timestamp=1435922627537, value=ABC                                                                                                            
 id2                                                         column=personal_data:age, timestamp=1435922670799, value=28                                                                                                                      
 id2                                                         column=personal_data:identification, timestamp=1435922670822, value=1235                                                                                                         
 id2                                                         column=personal_data:name, timestamp=1435922670773, value=loreto                                                                                                                 
 id2                                                         column=school_data:direction, timestamp=1435922671522, value=main street                                                                                                         
 id2                                                         column=school_data:identification, timestamp=1435922670850, value=ABCR                                                                                                           
 id3                                                         column=personal_data:age, timestamp=1435922697553, value=33                                                                                                                      
 id3                                                         column=personal_data:identification, timestamp=1435922697591, value=A1235                                                                                                        
 id3                                                         column=personal_data:name, timestamp=1435922697520, value=cristian                                                                                                               
 id3                                                         column=school_data:direction, timestamp=1435922698031, value=other street                                                                                                        
 id3                                                         column=school_data:identification, timestamp=1435922697608, value=TBCR                                                                                                           
3 row(s) in 0.0370 seconds
```

And my scala code is:

``` scala
object HbaseTest  extends App with Constants{


  val conf = new SparkConf()
    .setMaster(SPARK_IP)
    .setAppName("poc-hbase-test")
  val sc = new SparkContext(conf)
  val hbaseContext =  new HBaseSQLContext(sc) with Catalog
// This piece of code only must execute once in order to create the spark table metainfo.
  hbaseContext.read.format(DATASOURCE).options(
    Map("namespace" -> "", "tableName" -> "students", "hbaseTableName" -> "students",
      "colsSeq" -> "personal_data:name,personal_data:age,personal_data:identification,school_data:identification,school_data:direction",
      "keyCols" -> "personal_data:identification,string",
      "nonKeyCols" -> "personal_data:name,string,personal_data,name;personal_data:age,integer,personal_data,age;school_data:identification,string,school_data,identification;school_data:direction,string,school_data,direction"))
  .load

  System.out.println("First output")
   hbaseContext.sql("Select  `personal_data:name`, `personal_data:identification` as b, `personal_data:direction` as c from students").collect.foreach(println)
  System.out.println("Second output")
  hbaseContext.sql("Select  `personal_data:identification` as b from students").collect.foreach(println)
}

trait Catalog {
  _: SQLContext =>

  def getCatalog = catalog

}

trait Constants{
  val DATASOURCE = "org.apache.spark.sql.hbase.HBaseSource"
  val SPARK_IP = "local[4]"
}
```

The output is:

``` output
First output
[jose,,main street]
[loreto,,main street]
[cristian,,other street]
Second output
[]
[]
[]
```

I don't undertand why in the first output the second column is empty and why the second output all the rows are empty.

**Comment by yzhou2001** [comment] 2015-07-04 04:13
The fix is checked in. Thanks for reporting and helps on debugging.

**Comment by yzhou2001** [comment] 2015-07-05 07:25
@josegom The cause of the problem was that during load we add a null terminator to a string even as a sole, or the least significant, dimensional row key which misinterpreted a string rowkey in HBase that is not null terminated. This padding is unnecessary except for a string dimensional key that is not least significant. Performance impact as result of this padding should be negligible. After the removal of this padding, better support of existing HBase tables should be realized.

**Comment by yzhou2001** [comment] 2015-07-06 00:16
@josegom I made fixes to pad partial UTF8 string fields as (due to region split) region boundaries. This is needed due to the switch of use of Java's Unicode string to the UTF8 string in Spark 1.4. Please give it a try and report any problems you may find. Thanks!

**Comment by yzhou2001** [comment] 2015-07-06 06:06
@josegom The "age" field of your table only has 2 bytes, which, if declared as an "Integer" column as you do, causes the engine crash. If declared as a "short" column, however, the query succeeds but values returned appear to be wrong. Will check HBase's numerical encoding tomorrow.

**Comment by yzhou2001** [comment] 2015-07-06 16:32
@josegom It turns out to be not a problem. The HBase Shell I'm using somehow insert the "age" as a string through the command of: 

put 'students', 'id1', 'personal_data:age', 30

That's why I've got two byes of 51 and 48, the ASCII values of "30", and when cast to a 4-byte integer by our engine, an IndexOutOfBoundException was thrown.

**Closed as completed** 2015-07-11 00:04 UTC

**Comment by josegom** [comment] 2015-07-13 07:51
Hello,

I have tested it and all is right.

Thanks.
